### ISSUE TITLE
store command for sqlite not working, timeout?

### ISSUE THREAD

**Issue by mbodmer** [Ericsson/codechecker#1059]
Server side:

[16:36] - 127.0.0.1:44288 -- [HUMGSK] POST /****/v6.1/CodeCheckerService
[16:36] - 127.0.0.1:44298 -- [HUMGSK] POST /****/v6.1/CodeCheckerService
[ERROR] [16:36] - File ID for ***/abc.h is not found in the DB with content hash 0832d7b9619e0962dab86fc5020ca7dd2192be2de3cbecc0237e1725088aefd. Missing from ZIP?
[ERROR] [16:36] - File ID for ***/abc2.h is not found in the DB with content hash 71f645179ab1489c158b83cf4f858155af582ff4d52be3ec21e7def5aa0de7bf. Missing from ZIP?
[ERROR] [16:36] - File ID for ***/abc3.h is not found in the DB with content hash 003f934b263873ace48bef1c08ac2ce0eb9b69f7242346454066f1a3aeee4f5b. Missing from ZIP?
[ERROR] [16:36] - File ID for ***/abc4.h is not found in the DB with content hash 13b66efeaae02bc30bbe2c0019bcb4e320047d6d2b5f77e68ad5a678cd5cad29. Missing from ZIP?
[ERROR] [16:36] - File ID for ***/abc5.h is not found in the DB with content hash 8d250e32277774dbd8e8bc09e6f4b3ee28626ac3650e00f00a7cc79c582952c4. Missing from ZIP?
[ERROR] [16:36] - File ID for ***/abc6.h is not found in the DB with content hash acc9b97eb153ae155347258f6b50f0e96abc83e16daf9416b191d28a2318287b. Missing from ZIP?
[16:36] - Session timeout for run 1
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/src/codechecker/build/CodeChecker/lib/python2.7/libcodechecker/server/api/report_server.py", line 389, in _timeout_sessions
    self.abort_session(run_id)
  File "/usr/local/src/codechecker/build/CodeChecker/lib/python2.7/libcodechecker/server/api/report_server.py", line 361, in abort_session
    transaction.rollback()
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 828, in rollback
    self.transaction.rollback()
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 482, in rollback
    transaction._rollback_impl()
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 512, in _rollback_impl
    t[1].rollback()
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1563, in rollback
    self._do_rollback()
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1601, in _do_rollback
    self.connection._rollback_impl()
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/src/codechecker/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139991113467648 and this is thread id 139990398908160

Client, store command:

API call error: massStoreRun
RequestFailed(errorCode=2, _message='RequestFailed(errorCode=2, _message="\'NoneType\' object has no attribute \'filepath\'")')
[16:36] - Storage failed: RequestFailed(errorCode=2, _message='RequestFailed(errorCode=2, _message="\'NoneType\' object has no attribute \'filepath\'")')

**Comment by gyorb** [comment]
@mbodmer sorry for replying just now, but do you still have this problem?

**Comment by csordasmarton** [comment]
I think this is no longer a problem. Please try out our latest CodeChecker and if you still have this kind of problem please feel free to reopen this issue.
