### ISSUE TITLE
Improve client side error handling

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1205]
With this PR #1157 better error handling can be done in the web and command line clients.

The client api calls should be rechecked for proper error handling as @whisperity already mentioned, like in this case:
```
CodeChecker cmd runs --url whisperity
Internal server error on localhost:8001
Traceback (most recent call last):
  File "[...]/CodeChecker.py", line 101, in main
    args.func(args)
  File "[...]/libcodechecker/cmd/cmd_line_client.py", line 119, in handle_list_runs
    for run in runs:
TypeError: 'NoneType' object is not iterable
```

**Comment by whisperity** [comment]
**Note!** The client properly handles this. (It says "product cannot be used because it does not exist" and then quits.) I purposefully commented this handling out, to see the error returning from the server.

Most parts of the client is written preemptive: we check if the product/run exists, before actually querying from said product/run.
