### ISSUE TITLE
clang unknown arguments error

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1265]
Analysis failed on ubuntu by @niuzhi 

Dear Gyorgy Orban：
**I installed codechecker5.8 in ubuntu system, but when I run CodeChecker analyze, I report the following error. How to deal with this issue? Thank you

(venv) root@niuzhi:~# CodeChecker analyze ./compile.json -o ./results
[00:46] - Previous analysis results in '/root/results' have been removed, overwriting with current result
[00:46] - Starting static analysis ...
[ERROR] [00:46] - Analyzing dlqoscommon.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

[00:46] - [2/1235] clangsa analyzed global.c successfully.
[00:46] - [3/1235] clangsa analyzed CommQue.c successfully.
[ERROR] [00:46] - Analyzing dlschdmcm.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

[ERROR] [00:46] - Analyzing mcm_init.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

[ERROR] [00:46] - Analyzing dlcomp.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

**Comment by gyorb** [comment]
@niuzhi I highly recommend to update your CodeChecker version to our latest release and check again your project. There are many improvements and bug fixes since 5.8.

The problem is that gcc/g++ flags `-mno-sched-prolog`, `-mno-apcs-frame` are not handled by clang. To fix these errors we filter out the unsupported compiler arguments. Do you see any other unsupported arguments in your log?


`-mno-sched-prolog` should be already handled in our latest release.

**Comment by niuzhi** [comment]
@gyorb 
=========================Fist Question=================================
many unsupported arguments.for exanple:
-mno-apcs-frame -mno-apcs-frame -marm -mno-unaligned-access -mbig-endian and so on!!!
=================================================================

=========================Second Question==============================

I installed codechecker6.2 in ubuntu system, but when I run CodeChecker analyze,I report the following error?
(venv) root@niuzhi:~/CC# CodeChecker version
Kind | Version
Base package version | 6.2.0
Package build date | 2017-12-06T18:58
Git commit ID (hash) |
Git tag information | 6.2
Configuration schema | v6.0
Database schema | v6.0
Server supported API (Thrift) | 6.2
Client API (Thrift) | 6.2
(venv) root@niuzhi:/CC# CodeChecker analyze ./compile.json -o ./results
Traceback (most recent call last):
File "/root/codechecker-6.2/build/CodeChecker/cc_bin/CodeChecker.py", line 101, in main
args.func(args)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/libhandlers/analyze.py", line 393, in main
actions += log_parser.parse_log(log_file, parseLogOptions)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 294, in parse_log
actions = parse_compile_commands_json(logfile, parseLogOptions)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 259, in parse_compile_commands_json
get_compiler_target(parseLogOptions, results.compiler)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 169, in get_compiler_target
return parse_compiler_target(err)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 92, in parse_compiler_target
if line[0] == target_label:
IndexError: list index out of range
(venv) root@niuzhi:/CC#
===========================================================

**Comment by niuzhi** [comment]
@gyorb
@gyorb
=========================Fist Question=================================
many unsupported arguments.for exanple:
-mno-apcs-frame -mno-apcs-frame -marm -mno-unaligned-access -mbig-endian and so on!!!
=========================Second Question==============================

I installed codechecker6.2 in ubuntu system, but when I run CodeChecker analyze,I report the following error?
(venv) root@niuzhi:~/CC# CodeChecker version
Kind | Version
Base package version | 6.2.0
Package build date | 2017-12-06T18:58
Git commit ID (hash) |
Git tag information | 6.2
Configuration schema | v6.0
Database schema | v6.0
Server supported API (Thrift) | 6.2
Client API (Thrift) | 6.2
(venv) root@niuzhi:/CC# CodeChecker analyze ./compile.json -o ./results
Traceback (most recent call last):
File "/root/codechecker-6.2/build/CodeChecker/cc_bin/CodeChecker.py", line 101, in main
args.func(args)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/libhandlers/analyze.py", line 393, in main
actions += log_parser.parse_log(log_file, parseLogOptions)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 294, in parse_log
actions = parse_compile_commands_json(logfile, parseLogOptions)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 259, in parse_compile_commands_json
get_compiler_target(parseLogOptions, results.compiler)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 169, in get_compiler_target
return parse_compiler_target(err)
File "/root/codechecker-6.2/build/CodeChecker/lib/python2.7/libcodechecker/analyze/log_parser.py", line 92, in parse_compiler_target
if line[0] == target_label:
IndexError: list index out of range
(venv) root@niuzhi:/CC#

**Comment by niuzhi** [comment]
@gyorb
Dear gyorb，
I would like to consult how to add the -mno-sched-prolog parameter to the codechecker code project so that I can add many of these parameters to the codechecker code project！In this case I can eliminate the impact of these parameters  errors.Looking forward to your reply!

**Comment by gyorb** [comment]
@niuzhi In the `option_parser.py` file we have an dictionary where we collect the unknown options:
https://github.com/Ericsson/codechecker/blob/49bb70b2cd81ba8330a047d93d0a343c76ecb479/libcodechecker/log/option_parser.py#L141-L143

As you can see the `-mno-sched-prolog` option is already added to this collection:
https://github.com/Ericsson/codechecker/blob/49bb70b2cd81ba8330a047d93d0a343c76ecb479/libcodechecker/log/option_parser.py#L189-L192

Every argument which is not handled by clang should be there.

**Comment by niuzhi** [comment]
@gyorb 
OK ，thank you very much！！！
