### ISSUE TITLE
Removal of Default.sqlite causes exception on start if config database has rows

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#1386]
If I start a server and configure a postgresql-backed product, then delete the default product, stop the server, and also remove the `Default.sqlite` file, and then start the server again, the following happens:

1. The server recreates the `Default.sqlite` file, even though it's not needed.
2. Due to the server knowing it's not needed, it tries to call `create_initial_run_database` which throws an exception.

```
[INFO 2018-02-20 09:47] - Checking configuration database ...
[INFO 2018-02-20 09:47] - Database is up to date.
[ERROR 2018-02-20 09:47] - Database is up to date.
Traceback (most recent call last):
  File "/ssd/whisperity/CodeChecker/cc_bin/CodeChecker.py", line 93, in main
    args.func(args)
  File "/ssd/whisperity/CodeChecker/lib/python2.7/libcodechecker/libhandlers/server.py", line 388, in __handle
    main(args)
  File "/ssd/whisperity/CodeChecker/lib/python2.7/libcodechecker/libhandlers/server.py", line 864, in main
    server_init_start(args)
  File "/ssd/whisperity/CodeChecker/lib/python2.7/libcodechecker/libhandlers/server.py", line 785, in server_init_start
    cfg_sql_server, product_conn_string)
  File "/ssd/whisperity/CodeChecker/lib/python2.7/libcodechecker/server/server.py", line 958, in add_initial_run_database
    raise ValueError("Called create_initial_run_database on non-empty "
ValueError: Called create_initial_run_database on non-empty config database -- you shouldn't have done this!
```

After this, if the server is attempted to be started again, it will start, and the `Default` product will **NOT** be in the configuration &ndash; even though the file for exists.

My first hunch is that this was messed up when the new schema migration logic was implemented. The exception is rightful, the server should *not* add back a Default product if it was explicitly removed.

The control flow should be changed so this function is not called if not needed.

**Comment by whisperity** [comment]
Bump: This issue is still here with 6.11 release version, even if the server is not using Postgres.

My current scenario:
 - 2 products, SQLite, with an SQLite config database, neither is the `Default`
 - I had multiple products as archived databases which I deleted
 - I

**Comment by whisperity** [comment]
Bump: This issue is still here with 6.11 release version, even if the server is not using Postgres.

My current scenario:
 - 2 products, SQLite, with an SQLite config database, neither is the `Default`
 - I had multiple products as archived databases which I deleted
 - I noticed there is a `Default.sqlite` so I deleted that too
 - When starting the server up, I get the same issue as above `Create initial RUN database on non-empty CONFIG database`
 - Server crashes and I am back to prompt
 - When I start the server again, it properly starts and shows my two products in the log and on the server.
 - `Default.sqlite` recreated with empty schema, currently about 172K in size.

Neither of the two products I actively use is the `Default` one.

There is no reference to `Default` in the `config.sqlite` file.
