### ISSUE TITLE
"unsupported operand type(s)" when using a skipfile

### ISSUE THREAD

**Issue by MarkZ3** [Ericsson/codechecker#1529]
Using version 6.5.1
I am trying to run CodeChecker on the Clangd code base and filter-out the llvm and clang headers.

/foo/llvm/build$ CodeChecker parse -i SKIPFILE ./reports
[LOW] atomic_base.h:188:20: Value stored to '__b' during its initialization is never read [deadcode.DeadStores]
      memory_order __b = __m & __memory_order_mask;
                   ^

[LOW] atomic_base.h:199:20: Value stored to '__b' during its initialization is never read [deadcode.DeadStores]
      memory_order __b = __m & __memory_order_mask;
                   ^

Traceback (most recent call last):
  File "/foo/CodeChecker/cc_bin/CodeChecker.py", line 93, in main
    args.func(args)
  File "/foo/CodeChecker/lib/python2.7/libcodechecker/libhandlers/parse.py", line 156, in __handle
    main(args)
  File "/foo/CodeChecker/lib/python2.7/libcodechecker/libhandlers/parse.py", line 302, in main
    'print_steps' in args)
  File "/foo/CodeChecker/lib/python2.7/libcodechecker/libhandlers/parse.py", line 204, in parse
    report_stats = rh.write(files, reports, analyzed_source_file)
  File "/foo/CodeChecker/lib/python2.7/libcodechecker/analyze/plist_parser.py", line 379, in write
    LOG.debug(report + ' is skipped (in ' + f_path + ")")
TypeError: unsupported operand type(s) for +: 'Report' and 'str'
/foo/llvm/build$ cat SKIPFILE 
-/foo/llvm/include/*
-/foo/llvm/tools/clang/include/*

**Comment by gyorb** [comment]
Thanks for reporting this issue.

**Comment by MarkZ3** [comment]
Thanks! Is there a way to work around the issue? Or is a new release imminent?

**Comment by whisperity** [comment]
You can apply the diff manually and rebuild your CodeChecker install folder. Or simply commenting out the line that produces the issue also works, as this was only a debug log message that was badly formatted.
