### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'skip_file'

### ISSUE THREAD

**Issue by MarkZ3** [Ericsson/codechecker#1607]
Using version 6.7.0
I am trying to run CodeChecker on the Clangd code base with a "skipfile" argument.

/foo/llvm/build$ CodeChecker parse -i SKIPFILE ./reports
Traceback (most recent call last):
  File "/bar/CodeChecker/codechecker-64bit-6.7.0/cc_bin/CodeChecker.py", line 93, in main
    args.func(args)
  File "/bar/CodeChecker/codechecker-64bit-6.7.0/lib/python2.7/libcodechecker/libhandlers/parse.py", line 160, in __handle
    main(args)
  File "/bar/CodeChecker/codechecker-64bit-6.7.0/lib/python2.7/libcodechecker/libhandlers/parse.py", line 294, in main
    with open(args.skip_file, 'r') as skip_file:
AttributeError: 'Namespace' object has no attribute 'skip_file'

The SKIPFILE has:
```
-*/llvm/include/*
-*/llvm/tools/clang/include/*
-/usr/include/*
-/usr/local/include/*
```

**Comment by gyorb** [comment]
thanks for reporting this issue!
