### ISSUE TITLE
handle product error exceptions better and check the errors in the tests

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1632]
During the running of the tests I got these errors, they should be handled better and check why they happened.

```
19:13:03   File "libcodechecker/server/server.py", line 355, in do_POST
19:13:03     self.__check_prod_db(product)
19:13:03   File "libcodechecker/server/server.py", line 298, in __check_prod_db
19:13:03     raise ValueError(error_msg)
19:13:03 ValueError: 'producttest' database connection failed!
```
```
19:13:00 [ERROR 2018-06-07 19:13] - The product None does not exists
19:13:00 [ERROR 2018-06-07 19:13] - The product None does not exists
19:13:00 Traceback (most recent call last):
19:13:00   File "libcodechecker/server/server.py", line 355, in do_POST
19:13:00     self.__check_prod_db(product)
19:13:00   File "libcodechecker/server/server.py", line 270, in __check_prod_db
19:13:00     raise ValueError(error_msg)
19:13:00 ValueError: The product None does not exists
```

**Comment by bruntib** [comment]
This issue looks outdated. If something similar occurs, then we can create another ticket.
