### ISSUE TITLE
--update mode does not work with sqlite

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#227]
ednikru@md-mtas2:~/work/codechecker/TinyXML$ CodeChecker check --sqlite -w ~/.codechecker -b "make clean;make" -n tiny_v8 --update[INFO] - Starting build ...
rm -f core tinyxml.o tinyxmlparser.o xmltest.o tinyxmlerror.o tinystr.o xmltest
g++ -c -Wall -Wno-unknown-pragmas -Wno-format -O3   tinyxml.cpp -o tinyxml.o
g++ -c -Wall -Wno-unknown-pragmas -Wno-format -O3   tinyxmlparser.cpp -o tinyxmlparser.o
g++ -c -Wall -Wno-unknown-pragmas -Wno-format -O3   xmltest.cpp -o xmltest.o
xmltest.cpp: In function \u2018int main()\u2019:
xmltest.cpp:944:8: warning: variable \u2018loadOkay\u2019 set but not used [-Wunused-but-set-variable]
   bool loadOkay = doc.LoadFile();
        ^
xmltest.cpp:607:35: warning: ignoring return value of \u2018char* fgets(char*, int, FILE*)\u2019, declared with attribute warn_unused_result [-Wunused-result]
      fgets( savedBuf, 256, saved );
                                   ^
xmltest.cpp:980:32: warning: ignoring return value of \u2018char* fgets(char*, int, FILE*)\u2019, declared with attribute warn_unused_result [-Wunused-result]
    fgets( buf, 1024, textfile );
                                ^
g++ -c -Wall -Wno-unknown-pragmas -Wno-format -O3   tinyxmlerror.cpp -o tinyxmlerror.o
g++ -c -Wall -Wno-unknown-pragmas -Wno-format -O3   tinystr.cpp -o tinystr.o
g++ -o xmltest  tinyxml.o tinyxmlparser.o xmltest.o tinyxmlerror.o tinystr.o  
[INFO] - Build finished successfully.
[INFO] - Waiting for check results on [57045]
[INFO] - Incremental checking is in progress. The previous run results for tiny_v8 will be overwritten! 
[INFO] - Static analysis is starting ...
[INFO] - ClangSA analyzed tinyxmlerror.cpp successfully.
[INFO] - ClangSA analyzed xmltest.cpp successfully.
No handlers could be found for logger "thrift.server.TServer"
Traceback (most recent call last):
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/analysis_manager.py", line 113, in check
    rh.handle_results()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/analyzers/result_handler_plist_to_db.py", line 172, in handle_results
    suppress)
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/client.py", line 177, in add_report
    bug_type, severity, suppress)
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 360, in addReport
    return self.recv_addReport()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 382, in recv_addReport
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
    sz = self.readI32()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
    buff = self.trans.readAll(4)
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/thrift/transport/TTransport.py", line 58, in readAll
    chunk = self.read(sz - have)
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/thrift/transport/TTransport.py", line 159, in read
    self.__rbuf = StringIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/thrift/transport/TSocket.py", line 120, in read
    message='TSocket read 0 bytes')
TTransportException: TSocket read 0 bytes
Traceback (most recent call last):
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/analysis_manager.py", line 113, in check
    rh.handle_results()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/analyzers/result_handler_plist_to_db.py", line 52, in handle_results
    ' '.join(self.analyzer_cmd))
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/client.py", line 164, in add_build_action
    return self._client.addBuildAction(run_id, build_cmd, check_cmd)
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 315, in addBuildAction
    return self.recv_addBuildAction()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 341, in recv_addBuildAction
    raise result.requestError
RequestFailed: RequestFailed(_message="(sqlite3.OperationalError) database is locked [SQL: u'DELETE FROM build_actions WHERE build_actions.id = ?'] [parameters: (58,)]", error_code=0)
Traceback (most recent call last):
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/analysis_manager.py", line 113, in check
    rh.handle_results()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/analyzers/result_handler_plist_to_db.py", line 52, in handle_results
    ' '.join(self.analyzer_cmd))
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_lib/client.py", line 164, in add_build_action
    return self._client.addBuildAction(run_id, build_cmd, check_cmd)
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 315, in addBuildAction
    return self.recv_addBuildAction()
  File "/home/ednikru/work/codechecker/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 341, in recv_addBuildAction
    raise result.requestError
RequestFailed: RequestFailed(_message="(sqlite3.OperationalError) database is locked [SQL: u'DELETE FROM build_actions WHERE build_actions.id = ?'] [parameters: (59,)]", error_code=0)

**Comment by gyorb** [comment]
fixed during the update mode refractoring
