### ISSUE TITLE
CodeChecker check fails with python error

### ISSUE THREAD

**Issue by themightyoarfish** [Ericsson/codechecker#2528]
**Describe the bug**

I have a CMake project which I wish to check. I activate the venv, and run 
```
cd $PROJDIR
CodeChecker check -b "make -C build" -o results
```

This results in 
```
No handlers could be found for logger "system"
Traceback (most recent call last):
  File "/Users/rasmus/Downloads/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 111, in main
    subcommands[subcommand])
  File "/Users/rasmus/Downloads/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 47, in add_subcommand
    command_module.add_arguments_to_parser(sc_parser)
  File "/Users/rasmus/Downloads/codechecker/build/CodeChecker/cc_bin/../lib/python2.7/codechecker_analyzer/cmd/check.py", line 352, in add_arguments_to_parser
    if analyzer_types.is_ctu_capable(context):
  File "/Users/rasmus/Downloads/codechecker/build/CodeChecker/lib/python2.7/codechecker_analyzer/analyzers/analyzer_types.py", line 38, in is_ctu_capable
    clangsa_cfg = ClangSA.construct_config_handler([], context)
  File "/Users/rasmus/Downloads/codechecker/build/CodeChecker/lib/python2.7/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 360, in construct_config_handler
    checkers = ClangSA.get_analyzer_checkers(handler, environ)
  File "/Users/rasmus/Downloads/codechecker/build/CodeChecker/lib/python2.7/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 121, in get_analyzer_checkers
    alpha=True)
  File "/Users/rasmus/Downloads/codechecker/build/CodeChecker/lib/python2.7/codechecker_analyzer/analyzers/clangsa/clang_options.py", line 28, in get_analyzer_checkers_cmd
    major_version = clang_version_info.major_version
AttributeError: 'bool' object has no attribute 'major_version'
```

**CodeChecker version**
﻿﻿1d855af1d005b45a253637a6fa23cf01fbae9401

**To Reproduce**
Steps to reproduce the behaviour:

1. Clone repo
2. `make venv_osx`
3. Activate the venv
4. `make_package`
5. cd to cmake project
6. attempt to code check it
7. :(

**Expected behaviour**

The code is analyzed.

**Desktop (please complete the following information)**
 - OS: macOS 10.14.6

**Comment by csordasmarton** [comment]
@themightyoarfish I think #2487 pull request will solve your problem.

**Comment by gyorb** [comment]
@themightyoarfish could you check if these changes in #2538 will fix your issue 
PR #2538 will replace #2487

**Comment by csordasmarton** [comment]
@themightyoarfish I merged @gyorb pull request (#2538) to the master branch. Could you please try it again if it works for you?

**Comment by themightyoarfish** [comment]
During `make package` with the current master, I get `mv: cannot stat '/Users/rasmus/Downloads/codechecker/build/CodeChecker/www/userguide/gen-docs': No such file or directory`

**Comment by themightyoarfish** [comment]
However, when checking out 7a4260979c9391f1bdad0172ee69ee378a8bbd0b (which should be the head commit of the PR itself), the build is successful. Maybe another problem got introduced since the merge.

**Comment by themightyoarfish** [comment]
At the mentioned commit, I get the exact same error (clean build).

**Comment by themightyoarfish** [comment]
I get the exact same problem with 7a4260979c9391f1bdad0172ee69ee378a8bbd0b.

**Comment by csordasmarton** [comment]
Could you please send us the whole output of the `make package` command?

**Comment by themightyoarfish** [comment]
Very strange, running the process again, the `mv` problem disappeared.

**Comment by themightyoarfish** [comment]
I am currently unable to consistently reproduce the `mv` problem. Also the original problem from this issue seems to have disappeared. I am not sure if it has to do with me having llvm 9 installed and not 7 as instructed.

CodeChecker runs, but it doesn't do anything if `clang-tidy` is not available. This seems like something that could be checked during build time, no?

Anyway, I will close this for now and open a new issue if the problem reappears (or reopen this one).
