### ISSUE TITLE
Report converter crashes when converting corrupted cppcheck results

### ISSUE THREAD

**Issue by Szelethus** [Ericsson/codechecker#2571]
**Describe the bug**
After analyzing LLVM on the `llvmorg-9.0.0` tag with CppCheck on commit e9b7e7811be942b5ffe20d424baf0e2db30355bd with the following command:
```bash
$ cppcheck --enable=all --project=compile_commands.json --plist-output=results/cppcheck_pre -j12
```
converting fails:
```bash
$ report-converter --type cppcheck results/cppcheck_pre/AssemblerTest.plist -o results/cppcheck_results -v
Traceback (most recent call last):
  File "codechecker/tools/report-converter/venv/bin/report-converter", line 11, in <module>
    load_entry_point('report-converter', 'console_scripts', 'report-converter')()
  File "codechecker/tools/report-converter/codechecker_report_converter/cli.py", line 123, in main
    args.clean)       
  File "codechecker/tools/report-converter/codechecker_report_converter/cli.py", line 64, in output_to_plist
    parser.transform(analyzer_result, output_dir)
  File "codechecker/tools/report-converter/codechecker_report_converter/analyzer_result.py", line 35, in transform
    plist_objs = self.parse(analyzer_result)
  File "codechecker/tools/report-converter/codechecker_report_converter/cppcheck/analyzer_result.py", line 51, in parse
    file_to_plist_data[file_name] = plistlib.readPlist(f)
  File "/usr/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)                          
  File "/usr/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)       
xml.parsers.expat.ExpatError: junk after document element: line 364, column 8
 ```

Its worth noting that the plist file is incorrect -- I suspect running multiple jobs messes with CppCheck.

**CodeChecker version**
The report converter was built on commit 7cbfce477ccbfc0c2f0df59aacc031ba8a451d6d.

**Expected behavior**
Emit a proper error message about the incorrect file.

**Desktop (please complete the following information)**
 - OS: Ubuntu 18.04

**Additional context**
I generated the plist file on a server, but I could reproduce the crash by simply copying said plist file and trying to convert locally, so I attached it:
[AssemblerTest.zip](https://github.com/Ericsson/codechecker/files/4204754/AssemblerTest.zip)

**Comment by Szelethus** [comment]
Another crash due to an invalid plist file:
```bash
$ report-converter -t cppcheck random.plist -o results/
```
```
Traceback (most recent call last):
  File "/home/eumakri/codechecker/tools/report-converter/venv/bin/report-converter", line 11, in <module>
    load_entry_point('report-converter', 'console_scripts', 'report-converter')()
  File "/home/eumakri/codechecker/tools/report-converter/codechecker_report_converter/cli.py", line 123, in main
    args.clean)
  File "/home/eumakri/codechecker/tools/report-converter/codechecker_report_converter/cli.py", line 64, in output_to_plist
    parser.transform(analyzer_result, output_dir)
  File "/home/eumakri/codechecker/tools/report-converter/codechecker_report_converter/analyzer_result.py", line 39, in transform
    self._post_process_result(plist_objs)
  File "/home/eumakri/codechecker/tools/report-converter/codechecker_report_converter/analyzer_result.py", line 60, in _post_process_result
    self._add_report_hash(plist_objs)
  File "/home/eumakri/codechecker/tools/report-converter/codechecker_report_converter/cppcheck/analyzer_result.py", line 69, in _add_report_hash
    files[diag['location']['file']])
```
The problem here is that there are only 752 (value of `len(files)` files listed in the plist file, yet file 754 (value `diag['location']['file']` is referenced.

[random.zip](https://github.com/Ericsson/codechecker/files/4213778/random.zip)

**Comment by firewave** [comment]
I opened a ticket so this issue is tracked for Cppcheck itself - see https://trac.cppcheck.net/ticket/10019.

Which version of Cppcheck are you using? The one supplied by Ubuntu 18.04?

If you run into issue with it in the future please consider reporting it upstream - see https://trac.cppcheck.net/. Thanks.
