### ISSUE TITLE
Analysis fails with "NameError: name 'basestring' is not defined"

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#2656]
**Describe the bug**
Running codechecker, it is failing with:
```

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analysis_manager.py", line 593, in check
    actions_map)
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analysis_manager.py", line 312, in handle_failure
    tu_collector.zip_tu_files(zip_file, buildactions)
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python3/tu_collector/tu_collector.py", line 250, in zip_tu_files
    if isinstance(compilation_database, basestring):
NameError: name 'basestring' is not defined
```

**CodeChecker version**
9e33f21258f67f6426dcd30cf426e9bdeb6187b1
With python 3.7 on Debian

**Comment by csordasmarton** [comment]
@sylvestre We do not use `basestring` anymore. This line was changed in #2585 when porting to Python3. Please try to clean your package before building it:
```
make clean_package && make package
```

Also old virtual environments needs to be removed if you have not removed it yet:
- `rm -rf venv && make venv`
- `rm -rf venv_dev && make venv_dev`

**Comment by sylvestre** [comment]
OK, thanks
I restarted a new build. Seems to be fixed.

thanks
