### ISSUE TITLE
TypeError: unhashable type: 'dict' in codechecker_analyzer/analyzer.py", line 64, in create_actions_map

### ISSUE THREAD

**Issue by estoianovici** [Ericsson/codechecker#3050]
**Describe the bug**
Getting `TypeError: unhashable type: 'dict'` when running checker on a compile_comands.json file

This is the code:
```
    for act in actions:
        key = act.source, act.target[act.lang]
        if key in result:
            LOG.debug("Multiple entires in compile database "
                      "with the same (source, target) pair: (%s, %s)",
                      act.source, act.target)
        result[key] = act 
    return result
```

**CodeChecker version**

$ CodeChecker version

```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.16.0                                  
Package build date   | 2020-11-24T14:28                        
Git commit ID (hash) | dadbe9be3341e80e7045d45a48b6bc3df227dc1f
Git tag information  | 6.16                                    
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.16.0                                  
Package build date            | 2020-11-24T14:28                        
Git commit ID (hash)          | dadbe9be3341e80e7045d45a48b6bc3df227dc1f
Git tag information           | 6.16                                    
Server supported API (Thrift) | 6.35                                    
Client API (Thrift)           | 6.35                                    
-----------------------------------------------------------------------
```
**To Reproduce**
```
$ CodeChecker analyze compile_commands.json -o ./reports
[INFO 2020-11-24 15:03] - Enabled checkers:
clangsa: apiModeling.StdCLibraryFunctions, apiModeling.TrustNonnull, apiModeling.google.GTest, core.CallAndMessage, core.DivideZero, core.DynamicTypePropagation, core.NonNullParamChecker, core.NonnilStringConstants, core.NullDereference, core.StackAddressEscape, core.UndefinedBinaryOperatorResult, core.VLASize, core.builtin.BuiltinFunctions, core.builtin.NoReturnFunctions, core.uninitialized.ArraySubscript, core.uninitialized.Assign, core.uninitialized.Branch, core.uninitialized.CapturedBlockVariable, core.uninitialized.UndefReturn, cplusplus.InnerPointer, cplusplus.Move, cplusplus.NewDelete, cplusplus.NewDeleteLeaks, cplusplus.SelfAssignment, deadcode.DeadStores, nullability.NullPassedToNonnull, nullability.NullReturnedFromNonnull, optin.cplusplus.VirtualCall, optin.portability.UnixAPI, security.FloatLoopCounter, security.insecureAPI.UncheckedReturn, security.insecureAPI.getpw, security.insecureAPI.gets, security.insecureAPI.mkstemp, security.insecureAPI.mktemp, security.insecureAPI.rand, security.insecureAPI.vfork, unix.API, unix.Malloc, unix.MallocSizeof, unix.MismatchedDeallocator, unix.Vfork, unix.cstring.BadSizeArg, unix.cstring.NullArg, valist.CopyToSelf, valist.Uninitialized, valist.Unterminated
clang-tidy: bugprone-assert-side-effect, bugprone-bool-pointer-implicit-conversion, bugprone-copy-constructor-init, bugprone-dangling-handle, bugprone-dynamic-static-initializers, bugprone-fold-init-type, bugprone-forward-declaration-namespace, bugprone-forwarding-reference-overload, bugprone-inaccurate-erase, bugprone-incorrect-roundings, bugprone-infinite-loop, bugprone-integer-division, bugprone-lambda-function-name, bugprone-macro-repeated-side-effects, bugprone-misplaced-operator-in-strlen-in-alloc, bugprone-misplaced-widening-cast, bugprone-move-forwarding-reference, bugprone-not-null-terminated-result, bugprone-signed-char-misuse, bugprone-sizeof-container, bugprone-sizeof-expression, bugprone-string-constructor, bugprone-string-literal-with-embedded-nul, bugprone-suspicious-enum-usage, bugprone-suspicious-memset-usage, bugprone-suspicious-missing-comma, bugprone-suspicious-semicolon, bugprone-swapped-arguments, bugprone-terminating-continue, bugprone-throw-keyword-missing, bugprone-too-small-loop-variable, bugprone-undefined-memory-manipulation, bugprone-undelegated-constructor, bugprone-unused-raii, bugprone-unused-return-value, bugprone-use-after-move, bugprone-virtual-near-miss, cert-dcl54-cpp, cert-dcl58-cpp, cert-dcl59-cpp, cert-err09-cpp, cert-fio38-c, cert-mem57-cpp, cert-oop11-cpp, cert-oop58-cpp, cert-pos44-c, cppcoreguidelines-special-member-functions, google-build-namespaces, google-global-names-in-headers, misc-definitions-in-headers, misc-misplaced-const, misc-redundant-expression, misc-unconventional-assign-operator, misc-uniqueptr-reset-release, performance-inefficient-algorithm, performance-move-const-arg, performance-move-constructor-init, performance-no-automatic-move, performance-noexcept-move-constructor, performance-trivially-destructible
Traceback (most recent call last):
  File "/home/estoianovici/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 141, in main
    sys.exit(args.func(args))
  File "/home/estoianovici/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/analyze.py", line 1013, in main
    analyzer.perform_analysis(args, skip_handler, context, actions,
  File "/home/estoianovici/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzer.py", line 299, in perform_analysis
    actions_map = create_actions_map(actions, manager)
  File "/home/estoianovici/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzer.py", line 64, in create_actions_map
    if key in result:
  File "<string>", line 2, in __contains__
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
TypeError: unhashable type: 'dict'
```

**Comment by csordasmarton** [comment]
@estoianovici Could you please modify the source code and print the value of the `act` variable inside the for loop:
https://github.com/Ericsson/codechecker/blob/dadbe9be3341e80e7045d45a48b6bc3df227dc1f/analyzer/codechecker_analyzer/analyzer.py#L62

```py
for act in actions:
    print(act)
```
Please send us the value of this variable before the above exception happens.

**Comment by estoianovici** [comment]
I'll do it over the weekend. The issue happens with precompiled headers and unity builds enabled. I guess in those kinds of builds, the act.target[act.lang] ends up being a dictionary instead of a string value.

**Comment by csordasmarton** [comment]
#3184 should fix this problem because `act.target[act.lang]` is no longer a dict by default but a simple string. The patch is already merged on the master branch, so you can try it out.

I close this ticket for now but if you still experience this problem we can reopen it.
