### ISSUE TITLE
Following installation procedure does not give a working CodeChecker.

### ISSUE THREAD

**Issue by flok99** [Ericsson/codechecker#3108]
I installed a clean ubuntu-server 20.04.01.
Then I followed exactly the installation procedure on https://codechecker.readthedocs.io/en/latest/#linux
This gives the following errors:

```
Building wheels for collected packages: psutil, PyYAML
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/fhe/codechecker/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c8gzpufm/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c8gzpufm/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cg7173ht
       cwd: /tmp/pip-install-c8gzpufm/psutil/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
  Building wheel for PyYAML (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/fhe/codechecker/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c8gzpufm/PyYAML/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c8gzpufm/PyYAML/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xmbgmsf2
       cwd: /tmp/pip-install-c8gzpufm/PyYAML/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
Failed to build psutil PyYAML

```

Building codechecker WITHOUT venv seems to work, but the resulting program fails with "codechecker_api" not found.

**Comment by csordasmarton** [comment]
It seems that the wheel package is missing from your machine. Please install it and try it again:
```sh
sudo apt-get install python3-wheel
```

**Comment by flok99** [comment]
Unfortunately that does not seems to be the problem:

```
fhe@system:~/codechecker$ sudo apt-get install python3-wheel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-wheel is already the newest version (0.34.2-1).
0 upgraded, 0 newly installed, 0 to remove and 78 not upgraded.
```

**Comment by csordasmarton** [comment]
Maybe you can find more information about this problem here: https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

**Comment by flok99** [comment]
Ha, I tried a couple of the suggestions listed and there and the most unlikely one (export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages ) actually made the 'make venv' succeed!
I did not expect that one to be neccessary as /usr/lib/python3/dist-packages looks like a generic default path.
This indeed results in a build without errors. Running the program though gives other errors:

```
(venv) fhe@system:~/codechecker/build/CodeChecker/bin$ ./CodeChecker 
Couldn't import module for subcommand 'analyze'... ignoring.
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 109, in main
    add_subcommand(subparsers, subcommand,
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 39, in add_subcommand
    command_module = cmd_spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/analyze.py", line 21, in <module>
    from codechecker_analyzer import analyzer, analyzer_context, arg, env
  File "/home/fhe/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzer.py", line 29, in <module>
    from . import analysis_manager, pre_analysis_manager, env, checkers
  File "/home/fhe/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/pre_analysis_manager.py", line 26, in <module>
    from .analyzers.clangsa import ctu_manager, ctu_triple_arch
  File "/home/fhe/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/ctu_manager.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Couldn't import module for subcommand 'cmd'... ignoring.
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 109, in main
    add_subcommand(subparsers, subcommand,
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 39, in add_subcommand
    command_module = cmd_spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_client/cmd/cmd.py", line 19, in <module>
    from codechecker_api.codeCheckerDBAccess_v6 import ttypes
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/codechecker_api/codeCheckerDBAccess_v6/ttypes.py", line 10, in <module>
    from thrift.protocol.TProtocol import TProtocolException
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/thrift/protocol/TProtocol.py", line 24, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Couldn't import module for subcommand 'fixit'... ignoring.
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 109, in main
    add_subcommand(subparsers, subcommand,
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 39, in add_subcommand
    command_module = cmd_spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/fixit.py", line 19, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Couldn't import module for subcommand 'server'... ignoring.
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 109, in main
    add_subcommand(subparsers, subcommand,
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 39, in add_subcommand
    command_module = cmd_spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_server/cmd/server.py", line 23, in <module>
    from alembic import config
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context  # noqa
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 15, in <module>
    from .. import ddl
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql  # noqa
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/ddl/mssql.py", line 8, in <module>
    from .base import AddColumn
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/ddl/base.py", line 11, in <module>
    from ..util import sqla_compat
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/util/__init__.py", line 21, in <module>
    from .pyfiles import coerce_resource_to_filename  # noqa
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 5, in <module>
    from mako import exceptions
ModuleNotFoundError: No module named 'mako'
Couldn't import module for subcommand 'store'... ignoring.
Traceback (most recent call last):
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 109, in main
    add_subcommand(subparsers, subcommand,
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 39, in add_subcommand
    command_module = cmd_spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fhe/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_client/cmd/store.py", line 30, in <module>
    from codechecker_api.codeCheckerDBAccess_v6.ttypes import StoreLimitKind
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/codechecker_api/codeCheckerDBAccess_v6/ttypes.py", line 10, in <module>
    from thrift.protocol.TProtocol import TProtocolException
  File "/home/fhe/codechecker/venv/lib/python3.8/site-packages/thrift/protocol/TProtocol.py", line 24, in <module>
    import six
ModuleNotFoundError: No module named 'six'

```

**Comment by csordasmarton** [comment]
The `make venv` target should install all the dependencies. Try to clean your workspace `make clean clean_venv_dev` and try to follow the steps here: https://github.com/Ericsson/codechecker#linux

**Comment by flok99** [comment]
You probably mean "rm -rf venv"? Because make clean clean_venv_dev does not remove it.
Note that I'm exactly following the steps as listed at that page from the beginning.
Also re-doing the whole make venv etc does not give a different result. Again it complains about yaml, six and mako missing.

**Comment by csordasmarton** [comment]
Sorry, you installed `venv` and not `venv_dev`, so in this case you have to call the `make clean_venv` target which is the same as removing the venv directory with the `rm -rf venv` command.
The `make venv` target will create a python virtual env and it will install all the python requirements such as pyyaml:
https://github.com/Ericsson/codechecker/blob/79ea0aeacde9e9096df6b0eda10bed9859de721f/Makefile#L148-L151

What is the output of the `pip3 list | grep PyYAM` command?
What is the output of `python3 -c 'import sys; print(sys.path);'` command?

**Comment by flok99** [comment]
(venv) fhe@system:~/codechecker/build/CodeChecker/bin$ pip3 list | grep -i PyYAM
(venv) fhe@system:~/codechecker/build/CodeChecker/bin$ python3 -c 'import sys; print(sys.path);'
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/fhe/codechecker/venv/lib/python3.8/site-packages']

**Comment by csordasmarton** [comment]
What is the output of `which python3` command?
Did you source your venv (`source $PWD/venv/bin/activate`)?

**Comment by flok99** [comment]
(venv) fhe@system:~/codechecker/build/CodeChecker/bin$ which python3
/home/fhe/codechecker/venv/bin/python3
(venv) fhe@system:~/codechecker/build/CodeChecker/bin$ ls -la /home/fhe/codechecker/venv/bin/python3 
lrwxrwxrwx 1 fhe fhe 16 Dec 18 11:50 /home/fhe/codechecker/venv/bin/python3 -> /usr/bin/python3


And yes, I activated the venv.

**Comment by csordasmarton** [comment]
There was a change a couple of days ago which can be the problem: #3079. Could you please try to checkout the latest release version and try it out: `git checkout v6.15.0` whether it works or not in your machine.

**Comment by flok99** [comment]
Yes, that fixes all the problems!
E.g. ./CodeChecker server now shows output like:
[INFO 2020-12-18 13:36] - Checking configuration database ...
...without any errors.

Thanks a lot for your support!

**Comment by csordasmarton** [comment]
I tried to build the whole thing (master branch) in a docker container by using an ubuntu:20.04 image:
```sh
$ sudo docker run -ti --rm ubuntu:20.04 /bin/bash

# Install dependencies
$ apt-get update
$ apt-get install build-essential curl doxygen gcc-multilib git python3-dev python3-venv

# Get the repo.
$ git clone https://github.com/Ericsson/CodeChecker.git
$ cd CodeChecker/

# Create virtual env.
$ make venv
$ source $PWD/venv/bin/activate

# Build CodeChecker without the web UI.
$ BUILD_UI_DIST=NO make package

# Put the bin to the PATH.
$ export PATH="$PWD/build/CodeChecker/bin:$PATH"

# Check if the server command shows the help.
$ CodeChecker server

[INFO 2020-12-18 13:53] - Checking configuration database ...
[INFO 2020-12-18 13:53] - Database schema is missing.
```
And it works properly. So I don't really know what was the problem in your environment :/

> Note: to speed up the build I didn't installed clang and node dependencies and I skipped building the UI code.

**Comment by flok99** [comment]
Did you use ubuntu-server or ubuntu-desktop? Maybe there's a difference between those two?

**Comment by csordasmarton** [comment]
I used this docker image: https://hub.docker.com/_/ubuntu

**Comment by flok99** [comment]
I went through the ubuntu installer logfile and did not see any errors during installation.

**Comment by csordasmarton** [comment]
I also tried the following and it also worked for me:
```sh
# Start an ubuntu container.
$ sudo docker run -ti --rm ubuntu:20.04 /bin/bash

# Instal ubuntu server.
$ apt-get update && apt-get install -y ubuntu-server

# Same commands as in my previous comments
$ ...
```

One thing what needs to be mentioned that in both cases when I run the `make venv` command I saw similar error logs as you:
```
Building wheels for collected packages: psutil, PyYAML
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /CodeChecker/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3m1g8431/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3m1g8431/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9qv3qwrm
       cwd: /tmp/pip-install-3m1g8431/psutil/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
  Building wheel for PyYAML (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /CodeChecker/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3m1g8431/PyYAML/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3m1g8431/PyYAML/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ctxooci2
       cwd: /tmp/pip-install-3m1g8431/PyYAML/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
Failed to build psutil PyYAML
```

But CodeChecker commands are working properly.
