### ISSUE TITLE
CodeChecker fails after setup ccache

### ISSUE THREAD

**Issue by VladAdGad** [Ericsson/codechecker#3117]
**Describe the bug**
After setup of ccache
```
apt-get install ccache
/usr/sbin/update-ccache-symlinks
and change path "/usr/lib/ccache:${PATH}"
```
```
CodeChecker
Couldn't import module for subcommand 'analyze'... ignoring.
Traceback (most recent call last):
  File "/opt/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 109, in main
    add_subcommand(subparsers, subcommand,
  File "/opt/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 39, in add_subcommand
    command_module = cmd_spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/analyze.py", line 21, in <module>
    from codechecker_analyzer import analyzer, analyzer_context, arg, env
  File "/opt/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzer.py", line 29, in <module>
    from . import analysis_manager, pre_analysis_manager, env, checkers
  File "/opt/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analysis_manager.py", line 25, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "/opt/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 109, in main
    add_subcommand(subparsers, subcommand,
  File "/opt/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 46, in add_subcommand
    command_module.add_arguments_to_parser(sc_parser)
  File "/opt/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/check.py", line 454, in add_arguments_to_parser
    if analyzer_types.is_ctu_capable(context):
  File "/opt/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/analyzer_types.py", line 38, in is_ctu_capable
    clangsa_cfg = ClangSA.construct_config_handler([], context)
  File "/opt/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 411, in construct_config_handler
    checkers = ClangSA.get_analyzer_checkers(handler, environ)
  File "/opt/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 104, in get_analyzer_checkers
    checker_list_args = clang_options.get_analyzer_checkers_cmd(
  File "/opt/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/clang_options.py", line 39, in get_analyzer_checkers_cmd
    if cfg_handler.version_info.vendor != "clang":
AttributeError: 'bool' object has no attribute 'vendor'
```
**CodeChecker version**
3.15.0
and latest 75ef0ec24f9ef0f3ae6cd0e3fc57d04ab1114c21

**Desktop (please complete the following information)**
 - OS: Ubuntu20.04 Docker Image

**Comment by VladAdGad** [comment]
CC_LOGGER_GCC_LIKE="/usr/bin/ccache" solves the issue. Improve [documentation ](https://github.com/Ericsson/codechecker/blob/master/docs/analyzer/user_guide.md#ccache) or/and code needed.
