### ISSUE TITLE
codechecker store fails with ModuleNotFoundError: No module named 'store'

### ISSUE THREAD

**Issue by vahagnv** [Ericsson/codechecker#3274]
**Describe the bug**
`[test_out.zip](https://github.com/Ericsson/codechecker/files/6324840/test_out.zip)`
[INFO][2021-04-16 16:19:29] {system} [75925] <4567567872> - store.py:840 main() - Storing analysis results for run 'test'
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - product.py:143 split_product_url() - Parsing product url 'localhost:8001/Default'
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - product.py:178 split_product_url() - Result: With 'http' on server 'localhost:8001', product 'Default'
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - credential_manager.py:61 __init__() - Loading clientside session config.
[INFO][2021-04-16 16:19:29] {system} [75925] <4567567872> - credential_manager.py:65 __init__() - Checking local passwords or tokens in /Users/vahag/.codechecker.passwords.json
[INFO][2021-04-16 16:19:29] {system} [75925] <4567567872> - credential_manager.py:90 __init__() - Password file not found.
[INFO][2021-04-16 16:19:29] {system} [75925] <4567567872> - credential_manager.py:99 __init__() - Checking for local valid sessions.
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - credential_manager.py:113 __init__() - Found session information for these hosts:
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - client.py:240 setup_client() - Initializing client connecting to localhost:8001/Default done.
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - store.py:850 main() - Will write mass store ZIP to '/var/folders/j_/2f9w6ybx35d2t067pl_91nn80000gn/T/tmpvfvu1bvy.zip'...
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - store.py:853 main() - Assembling zip file.
[DEBUG][2021-04-16 16:19:29] {system} [75925] <4567567872> - store.py:580 assemble_zip() - Processing report files ...
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 237, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'store'
A process in the process pool was terminated abruptly while the future was running or pending.
  File "/Users/vahag/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 174, in <module>
    main(commands)
  File "/Users/vahag/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 141, in main
    sys.exit(args.func(args))
  File "/Users/vahag/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_client/cmd/store.py", line 859, in main
    traceback.print_stack()
[ERROR][2021-04-16 16:19:29] {system} [75925] <4567567872> - store.py:860 main() - Failed to assemble zip file.
(CodeChecker venv) 

**CodeChecker version**
Y6.16.0

**To Reproduce**
Steps to reproduce the behaviour:

1. run local server (localhost::8001)-> `codechecker server`
2. unzip attached archive 
[test_out.zip](https://github.com/Ericsson/codechecker/files/6324984/test_out.zip)

3.  run -> `codechecker store   test_out   -n test  --verbose debug` 

**Expected behaviour**
Report stored to database

**Desktop (please complete the following information)**
 - OS: [macos]
 - Browser: [Chrome]
 - Version: [latest]

**Additional context**
Add any other context about the problem.

**Comment by csordasmarton** [comment]
@vahagnv What happens if you analyze a simple file and store the results to your server. Do you still get this error?

Example code:
```cpp
// main.cpp
int main()
{
  sizeof(42);
  return 1 / 0;
}
```
- Log your project: `CodeChecker log -b "g++ main.cpp" -o ./compilation_database.json`
- Analyze your project: `CodeChecker analyze ./compilation_database.json -o ./reports`
- Store the results: `CodeChecker store -n myrun ./reports`

**Comment by vahagnv** [comment]
Got the same error.

**Comment by csordasmarton** [comment]
@vahagnv Do you get the same error with older version of CodeChecker (e.g.: 6.15.0)?

**Comment by vahagnv** [comment]
Got some error on 6.15.2

**Comment by csordasmarton** [comment]
I think the problem comes from here:
https://github.com/Ericsson/codechecker/blob/472a7e8cd4f2c287acf8aeec566aa22504912983/web/client/codechecker_client/cmd/store.py#L545

Can you please try to debug it? Try to insert some print statement before and after this *with* statement to make sure that the problem comes from here. Also you can try to insert some try/except code blocks here and print the traceback.

Unfortunately we don't have an osx machine to reproduce this problem.

**Comment by vahagnv** [comment]
I've change with `concurrent.futures.ProcessPoolExecutor() as executor` part with sequential code and it worked.

**Comment by csordasmarton** [comment]
I just googled on this problem and I found this: https://stackoverflow.com/questions/64501481/python-concurrent-futures-processpoolexecutor-and-global-variables-works-on-lin

> Changed in version 3.8: On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess. See bpo-33725.

What happens if you configure the context explicitly and set it to fork?

```py
import multiprocessing as mp
...

with concurrent.futures.ProcessPoolExecutor(mp_context=mp.get_context('fork')) as executor:
    ...
```

**Comment by vahagnv** [comment]
Thank you. That's fixed the issue.

**Comment by Mekhak** [comment]
Hi All,

Any updates on fixing this on macOS (python > 3.8)?

**Comment by gamesh411** [comment]
#4883 fixes this.
