### ISSUE TITLE
LeakSanitizer can not effect

### ISSUE THREAD

**Issue by basakerhz** [Ericsson/codechecker#3373]
**Describe the bug**
LSAN can not effect

**CodeChecker version**
compile with newest code
I'm sure that there are so many leak issues, but I can not convert them.

![image](https://user-images.githubusercontent.com/74943560/124855800-1307a780-dfdc-11eb-8956-17162b2467ff.png)
![image](https://user-images.githubusercontent.com/74943560/124856004-6548c880-dfdc-11eb-8caf-f745872aa28a.png)

**Comment by basakerhz** [comment]
anything wrong?😭
![image](https://user-images.githubusercontent.com/74943560/124867525-d85c3a00-dff0-11eb-90a2-464a4ea969fc.png)

**Comment by csordasmarton** [comment]
@basakerhz Can you please share us the `all.log` file or at least one full log for a LeakSanitizer bug?

**Comment by basakerhz** [comment]
Sorry, I can not copy it out because of the limited access, actually I can not even convert this test file: 
[https://github.com/Ericsson/codechecker/blob/master/tools/report-converter/tests/unit/lsan_output_test_files/lsan.out](url)
I am not sure that whether I lost some environment variables or any other steps.

**Comment by csordasmarton** [comment]
Try to step into this directory `tools/report-converter/tests/unit/lsan_output_test_files` and run the command again. This lsan.out file contains a relative file path which can be found only if you are in the right directory:
https://github.com/Ericsson/codechecker/blob/69dd2895635eb717de6bd423f50d008383a10bd5/tools/report-converter/tests/unit/lsan_output_test_files/lsan.out#L4

If no file path can be found when parsing the stack trace of a leak sanitizer output our tool will not be able to generate a report from it.

**Comment by basakerhz** [comment]
Thanks, it worked on lsan.out, but it still can not effect in my code😪, I found that the main difference between lsan.out and my own lsan output result is that almost all path in my lasan-report are absolute path ,not relative path like lsan.out, is that has influence to report-converter?

**Comment by csordasmarton** [comment]
@basakerhz It's not a problem if the file paths are absolute paths. However it is hard to tell you what can be the problem if you can't share the output file with us.

**Comment by basakerhz** [comment]
Yes, I can understand, I will check my problem on my own, thanks again😄.

**Comment by jay24rajput** [comment]
@balazske There might be some extra spaces between the two consecutive lines in your output. Something like this:
```
==27372==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x49532d in malloc (/media/jay/New-Volume/linux-5.9-rc1/a.out+0x49532d)
    #1 0x4c4f68 in main /media/jay/New-Volume/linux-5.9-rc1/lsan.c:3:7
    #2 0x7fa4ae6680b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 7 byte(s) leaked in 1 allocation(s).
```

In such cases, you can just remove the blank lines and the sanitizer will hopefully work like a charm 😃 😛

**Comment by basakerhz** [comment]
@jay24rajput You are right! There is always a blank line between the top line and the detail line in my lsan output , after I removed the blank line, it can be converted correctly, really appreciate you !😆
