### ISSUE TITLE
TypeError: cannot pickle '_thread._local' object

### ISSUE THREAD

**Issue by HoLo-Debris** [Ericsson/codechecker#3542]
**Describe the bug**
When I use the command `codechecker server` I got this error. Here are the details:
`
[INFO 2021-12-08 18:09] - Checking configuration database ...
[INFO 2021-12-08 18:09] - Database is up to date.
[INFO 2021-12-08 18:09] - Status of products:
-------------------------------------------------------------------------------------------------------------------------------------------------------
Product endpoint | Database status         | Database location                         | Schema version in the database | Schema version in the package
-------------------------------------------------------------------------------------------------------------------------------------------------------
Default          | Database is up to date. | /Users/debris/.codechecker/Default.sqlite | fb356f0eefed (up to date)      | fb356f0eefed                 
-------------------------------------------------------------------------------------------------------------------------------------------------------
[INFO 2021-12-08 18:09] - Garbage collection for product 'Default' started...
[INFO 2021-12-08 18:09] - Garbage collection finished.
[INFO 2021-12-08 18:09] - Searching for SSL key at /Users/debris/.codechecker/key.pem, cert at /Users/debris/.codechecker/cert.pem, not found...
[INFO 2021-12-08 18:09] - Falling back to simple, insecure HTTP.
[INFO 2021-12-08 18:09] - Server waiting for client requests on [localhost:8001]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/codechecker_common/cli.py", line 206, in main
    sys.exit(args.func(args))
  File "/opt/homebrew/lib/python3.9/site-packages/codechecker_server/cmd/server.py", line 436, in __handle
    main(args)
  File "/opt/homebrew/lib/python3.9/site-packages/codechecker_server/cmd/server.py", line 1002, in main
    server_init_start(args)
  File "/opt/homebrew/lib/python3.9/site-packages/codechecker_server/cmd/server.py", line 972, in server_init_start
    server.start_server(args.config_directory,
  File "/opt/homebrew/lib/python3.9/site-packages/codechecker_server/server.py", line 1088, in start_server
    p.start()
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread._local' object
`

**CodeChecker version**
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.18.0                                  
Package build date      | 2021-11-12T13:13                        
Git commit ID (hash)   | 153b0e09efc715fd16eee815eecf454f9f79f7f1
Git tag information      | 6.18                                    
---------------------------------------------------------------

**To Reproduce**
Steps to reproduce the behaviour: 
1. Run command 'codechecker server'
2. See error

**Expected behaviour**
I want to start the service and visit the webpage of codechecker through typing http://localhost:8001 in my browser.

**Desktop (please complete the following information)**
 - OS: macOS Big Sur Version 11.4
 - Browser: Chrome

**Additional context**
I install the codechecker through the command `pip install codechecker` according [here](https://github.com/Ericsson/codechecker)
The version of pip :
->pip -V                                                                                                                                                                       ─╯
pip 21.3.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)

**Comment by HoLo-Debris** [comment]
There seems something wrong with the _Popen function in  File "/Users/debris/miniconda3/lib/python3.8/multiprocessing/process.py" at line 77:
```
def _Popen(self):
    raise NotImplementedError
```
But I don't know how to fix if

**Comment by MisterMartin** [comment]
I encountered the same error on MacOS Monterey. Was able to get the server to run by using python3.7.

**Comment by whisperity** [comment]
@y-Adrian @MisterMartin Could you please retry using a newer CodeChecker version? We have recently changed multiprocessing-related library in 6.23: #4076, #4118.

**Comment by bruntib** [comment]
I close this ticket due to inactivity. CodeChecker server is supposed to run in OSX, too.
