### ISSUE TITLE
Error on CodeChecker parse -e html

### ISSUE THREAD

**Issue by jimis** [Ericsson/codechecker#3606]
The output is:
```
+ CodeChecker parse -e html --trim-path-prefix /path/to/src/ -o /path/to/html_reports /path/to/results
Traceback (most recent call last):
  File "codechecker/build/CodeChecker/lib/python3/codechecker_common/cli.py", line 208, in main
    sys.exit(args.func(args))
  File "codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/cmd/parse.py", line 443, in main
    html_builder.finish(output_dir_path, statistics)
AttributeError: 'NoneType' object has no attribute 'finish'
```

CodeChecker is 6.18.2.

EDIT: It seems `CodeChecker log` did not log any command because of a build system issue, so no files were compiled.

**Comment by jimis** [comment]
Thanks!
