### ISSUE TITLE
When using an incorrect port, "cmd sum" should give an explicit message instead of a backtrace

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#368]
```
$ CodeChecker cmd sum -p 5432 -a
Traceback (most recent call last):
  File "/data/jenkins/codechecker_package/CodeChecker/cc_bin/CodeChecker.py", line 372, in main
    args.func(args)
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/cmdline_client/cmd_line_client.py", line 191, in handle_list_result_types
    client = setupClient(args.host, args.port, '/')
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/cmdline_client/cmd_line_client.py", line 44, in setupClient
    if not check_API_version(client):
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/cmdline_client/cmd_line_client.py", line 21, in check_API_version
    version = client.getAPIVersion()
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/cmdline_client/thrift_helper.py", line 36, in wrapper
    res = func(*args, **kwargs)
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_gen/codeCheckerDBAccess/codeCheckerDBAccess.py", line 796, in getAPIVersion
    return self.recv_getAPIVersion()
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_gen/codeCheckerDBAccess/codeCheckerDBAccess.py", line 806, in recv_getAPIVersion
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/var/lib/jenkins/checker_env/local/lib/python2.7/site-packages/thrift/protocol/TJSONProtocol.py", line 318, in readMessageBegin
    self.readJSONArrayStart()
  File "/var/lib/jenkins/checker_env/local/lib/python2.7/site-packages/thrift/protocol/TJSONProtocol.py", line 306, in readJSONArrayStart
    self.readJSONSyntaxChar(LBRACKET)
  File "/var/lib/jenkins/checker_env/local/lib/python2.7/site-packages/thrift/protocol/TJSONProtocol.py", line 211, in readJSONSyntaxChar
    current = self.reader.read()
  File "/var/lib/jenkins/checker_env/local/lib/python2.7/site-packages/thrift/protocol/TJSONProtocol.py", line 140, in read
    self.data = self.protocol.trans.read(1)
  File "/var/lib/jenkins/checker_env/local/lib/python2.7/site-packages/thrift/transport/THttpClient.py", line 97, in read
    return self.__http.file.read(sz)
AttributeError: 'NoneType' object has no attribute 'read'
```

Happy to help if needed

**Comment by sylvestre** [comment]
This was caused by using the wrong port (postgresql here)

**Comment by dkrupp** [comment]
A meaningful error message would be useful anyway.

**Comment by gyorb** [comment]
Did you manage to get the summary with the right port number?

**Comment by sylvestre** [comment]
Yes, I did

**Comment by gyorb** [comment]
Great!

**Comment by sylvestre** [comment]
Hmm, I think this should not be closed. We should not get a backtrace but a clear error message "could not reach the http server"
