### ISSUE TITLE
[6.19 Regression][analyze] Compilation database deemed invalid just because it contains assembly files (`.S`)

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#3730]
**Describe the bug**
When using the CMake-generated (`-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`) `compile_commands.json` for [the LLVM project](http://github.com/llvm/llvm-project), the analysis fails with `ERROR: The compile database is not valid.`

**CodeChecker version**
6.19.1 (commit 9fa0f9817f6e91eda2a9202e0a3bf5006accdc8c) and 6.20.0-rc1 (commit d24c22cd39a9e7a9145c5293843c6450e31862db) are affected.

Version 6.18.1 (commit fd5f7e04219f947cfda68e9e11f4d3b07f0564a5) works fine.

**To Reproduce**
Steps to reproduce the behaviour:

1. Fetch the LLVM project and check out the master branch.
2. Create a compile commands database by CMake. Make sure to add `clang` and `clang-tools-extra` to the `-DLLVM_ENABLE_PROJECTS` variable. 
3. Run `CodeChecker analyze Build/compile_commands.json`

**Expected behaviour**
The analysis continues to work as normal. If the language of a file is impossible to determine, that job should be skipped. Also, it should not require a `--verbose debug` to figure out what the issue is, because the detail is hidden by saying that "the compilation database is not valid".

**Desktop (please complete the following information)**
 - OS: Ubuntu 18.04.6 LTS

**Additional context**
Running with `--verbose debug` seems to show that something changed wrt. how the defaults for a compiler is obtained. With **6.18** the log starts with the following, before going on to spawn the analysers:

```
[DEBUG][2022-08-30 14:29:17] {system} [4377] <140185855609728> - analyze.py:954 main() - Output will be stored to: '/home/whisperity/tmp'
[DEBUG][2022-08-30 14:29:18] {buildlogger} [4377] <140185855609728> - log_parser.py:390 get_compiler_includes() - Retrieving default includes via '/usr/bin/c++ -std=c++1z -E -x c - -v '
[DEBUG][2022-08-30 14:29:18] {buildlogger} [4377] <140185855609728> - log_parser.py:390 get_compiler_includes() - Retrieving default includes via '/usr/bin/c++ -std=c++1z -E -x c++ - -v '
[DEBUG][2022-08-30 14:29:18] {buildlogger} [4377] <140185855609728> - log_parser.py:390 get_compiler_includes() - Retrieving default includes via '/usr/bin/cc  -E -x c - -v '
[DEBUG][2022-08-30 14:29:18] {buildlogger} [4377] <140185855609728> - log_parser.py:390 get_compiler_includes() - Retrieving default includes via '/usr/bin/cc  -E -x c++ - -v '
[DEBUG][2022-08-30 14:29:44] {buildlogger} [4377] <140185855609728> - log_parser.py:1361 parse_unique_log() - Writing compiler info into:/home/whisperity/tmp/compiler_info.json
[DEBUG][2022-08-30 14:29:44] {buildlogger} [4377] <140185855609728> - log_parser.py:1364 parse_unique_log() - Parsing log file done.
```

whereas with **6.19.1** or **6.20.0-rc1**, the output is:

```
[DEBUG][2022-08-30 14:30:40] {system} [9093] <139697077787520> - analyze.py:972 main() - Output will be stored to: '/home/whisperity/tmp'
[DEBUG][2022-08-30 14:30:40] {buildlogger} [9093] <139697077787520> - log_parser.py:418 get_compiler_includes() - Retrieving default includes via /usr/bin/c++ -std=c++1z -E -x c++ - -v
[DEBUG][2022-08-30 14:30:41] {buildlogger} [9093] <139697077787520> - log_parser.py:418 get_compiler_includes() - Retrieving default includes via /usr/bin/cc -E -x c - -v
[DEBUG][2022-08-30 14:30:41] {buildlogger} [9093] <139697077787520> - log_parser.py:418 get_compiler_includes() - Retrieving default includes via /usr/bin/cc -E -x '' - -v
[ERROR][2022-08-30 14:30:41] {buildlogger} [9093] <139697077787520> - log_parser.py:1349 parse_unique_log() - The compile database is not valid.
[DEBUG][2022-08-30 14:30:41] {buildlogger} [9093] <139697077787520> - log_parser.py:1350 parse_unique_log() - Traceback (most recent call last):
  File "codechecker_analyzer/buildlog/log_parser.py", line 1287, in parse_unique_log
    action = parse_options(entry,
  File "codechecker_analyzer/buildlog/log_parser.py", line 1076, in parse_options
    ImplicitCompilerInfo.set(details, compiler_info_file)
  File "codechecker_analyzer/buildlog/log_parser.py", line 573, in set
    'compiler_includes': ICI.get_compiler_includes(
  File "codechecker_analyzer/buildlog/log_parser.py", line 422, in get_compiler_includes
    include_dirs = ICI.__parse_compiler_includes(cmd)
  File "codechecker_analyzer/buildlog/log_parser.py", line 378, in __parse_compiler_includes
    lines = ImplicitCompilerInfo.__get_compiler_err(compile_cmd)
  File "codechecker_analyzer/buildlog/log_parser.py", line 342, in __get_compiler_err
    proc = subprocess.Popen(
  File "subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

It seems that for some files in the build log, the language is misdetected as "empty string":

    Retrieving default includes via /usr/bin/cc -E -x '' - -v

and indeed, running this command results in an error:

```
❯ /usr/bin/cc -E -x '' - -v
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
cc: error: language  not recognized
cc: error: language  not recognized
```

Inspecting the JSON manually, it seems there are 4 `.S` files in the log:

```
❯ cat compile_commands.json | \
    lpython -t json "for E in DATA: print(E['file'].split('.')[-1]); endfor; DATA = None;" | \
    sort | uniq -c | sort -hr

   4275 cpp
     33 c
     22 cc
      4 S
```

```
❯ cat compile_commands.json | \
    lpython -t json "for E in DATA: if E['file'].split('.')[-1] == 'S': print(E['file']); endif; endfor; DATA = None;"

llvm/lib/Support/BLAKE3/blake3_sse2_x86-64_unix.S
llvm/lib/Support/BLAKE3/blake3_sse41_x86-64_unix.S
llvm/lib/Support/BLAKE3/blake3_avx2_x86-64_unix.S
llvm/lib/Support/BLAKE3/blake3_avx512_x86-64_unix.S
```

The `ld-logger` version of the build database works fine.
If I manually remove the offending entries from the build log, the analysis starts.

**Comment by flaviut** [comment]
Not sure if this is ultimately the right solution, but I'm working around this with the following patch:

```diff
--- a/codechecker_analyzer/buildlog/log_parser.py
+++ b/codechecker_analyzer/buildlog/log_parser.py
@@ -570,6 +570,8 @@
             ICI.load_compiler_info(compiler_info_file)
         else:
             if iisk not in ICI.compiler_info:
+                if iisk.language is None:
+                    return
                 ICI.compiler_info[iisk] = {
                     'compiler_includes': ICI.get_compiler_includes(
                         iisk.compiler, iisk.language, iisk.compiler_flags),
```
