### ISSUE TITLE
Starting CodeChecker with deleted `Default.sqlite` but existing config throws exception

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#3810]
**Describe the bug**
If the auto-create `Default.sqlite` is removed but the `config.sqlite` still contains the product record, the next server start throws an error.

**CodeChecker version**
6.21

**To Reproduce**
Steps to reproduce the behaviour:

1. `CodeChecker server -f ~/dummy`
2. Everything is fine, server starts and creates the initial configuration (1 "Default" product). Kill it.
3. `rm ~/dummy/Default.sqlite`
4. Start it again: `CodeChecker server -f ~/dummy`
5. Error thrown, server quits immediately.
6. Start it again: `CodeChecker server -f ~/dummy`
7. Everything is fine, and the file is recreated.

The error in full:

```
[INFO 2023-01-06 15:15] - Checking configuration database ...
[INFO 2023-01-06 15:15] - Database is up to date.
Traceback (most recent call last):
  File "/home/midya/CodeChecker/build/CodeChecker/lib/python3/codechecker_common/cli.py", line 209, in main
    sys.exit(args.func(args))
  File "/home/midya/CodeChecker/build/CodeChecker/lib/python3/codechecker_server/cmd/server.py", line 421, in __handle
    main(args)
  File "/home/midya/CodeChecker/build/CodeChecker/lib/python3/codechecker_server/cmd/server.py", line 988, in main
    server_init_start(args)
  File "/home/midya/CodeChecker/build/CodeChecker/lib/python3/codechecker_server/cmd/server.py", line 910, in server_init_start
    cfg_sql_server, product_conn_string)
  File "/home/midya/CodeChecker/build/CodeChecker/lib/python3/codechecker_server/server.py", line 1151, in add_initial_run_database
    raise ValueError("Called create_initial_run_database on non-empty "
ValueError: Called create_initial_run_database on non-empty config database -- you shouldn't have done this!
```

**Desktop (please complete the following information)**
 - OS: Debian 10
 - Python 3.7.3

**Comment by bruntib** [comment]
I close this as a duplicate of https://github.com/Ericsson/codechecker/issues/1386
