### ISSUE TITLE
CodeChecker `-o` options does not create parent path of the output file if not existing

### ISSUE THREAD

**Issue by julian-poidevin** [Ericsson/codechecker#3856]
**Describe the bug**
CodeChecker `-o` options does not create path if not existing. For example, when running :
```
CodeChecker log -b "make release" -o "./build/codechecker/compilation_database.json"
```
when the `build` folder does not exist, the command fails with the following error :

```
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/codechecker_common/cli.py", line 209, in main
    sys.exit(args.func(args))
  File "/home/vscode/.local/lib/python3.10/site-packages/codechecker_analyzer/cmd/log.py", line 173, in main
    with open(args.logfile, 'w',
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/batcom-bootloader/build/codechecker/compilation_database.json'
```

**CodeChecker version**
```
[INFO 2023-03-13 09:58] - CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.21.0-rc                               
Package build date   | 2022-11-09T15:50                        
Git commit ID (hash) | f787140b2320885a63d10a325377c6d3999b2856
Git tag information  | 6.21                                    
---------------------------------------------------------------
[WARNING 2023-03-13 09:58] - This version is only a release candidate! If you encounter any problems, please submit a bug report!

[INFO 2023-03-13 09:58] - CodeChecker web version:
------------------------------------------------------------------------------
Kind                                | Version                                 
------------------------------------------------------------------------------
Base package version                | 6.21.0-rc                               
Package build date                  | 2022-11-09T15:50                        
Git commit ID (hash)                | f787140b2320885a63d10a325377c6d3999b2856
Git tag information                 | 6.21                                    
Server supported Thrift API version | 6.51                                    
Client Thrift API version           | 6.51                                    
------------------------------------------------------------------------------
[WARNING 2023-03-13 09:58] - This version is only a release candidate! If you encounter any problems, please submit a bug report!
```
**To Reproduce**
Steps to reproduce the behaviour:

1. Have a workspace without a `build` folder
2. Run command '`CodeChecker log -b "make release" -o "./build/codechecker/compilation_database.json"`'
3. The command fails with the following error :
  ```
  Traceback (most recent call last):
    File "/home/vscode/.local/lib/python3.10/site-packages/codechecker_common/cli.py", line 209, in main
      sys.exit(args.func(args))
    File "/home/vscode/.local/lib/python3.10/site-packages/codechecker_analyzer/cmd/log.py", line 173, in main
      with open(args.logfile, 'w',
  FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/batcom-bootloader/build/codechecker/compilation_database.json'
  ```

4. Create the path using `mkdir -p build/codechecker/`
5. Run the command again '`CodeChecker log -b "make release" -o "./build/codechecker/compilation_database.json"`'
6. The command succeeds 

**Expected behaviour**
The command should create the parent directories when providing a `compilation_database.json` path that does not exists

**Desktop (please complete the following information)**
 - OS: ArchLinux

**Additional context**
N/A

**Comment by mhammadtariq11** [comment]
@bruntib 
I'm working on this. Please assign it to me.
