### ISSUE TITLE
Codechecker v6.22.2 doesn't work on Windows 

### ISSUE THREAD

**Issue by AlexanderChamara322** [Ericsson/codechecker#4068]
**Describe the bug**
During source code analyzing CodeChecker fail with an error "AttributeError: module 'os' has no attribute 'uname'"

**CodeChecker version**
v6.22.2

**To Reproduce**
C:\>CodeChecker analyze project/build/release/compile_commands.json --enable sensitive --output reports
Traceback (most recent call last):
  File "c:\python\lib\site-packages\codechecker_common\cli.py", line 167, in main
    add_subcommand(subparsers, subcommand,
  File "c:\python\lib\site-packages\codechecker_common\cli.py", line 57, in add_subcommand
    command_module.add_arguments_to_parser(sc_parser)
  File "C:\Python\Lib\site-packages\codechecker_analyzer/cmd\analyze.py", line 456, in add_arguments_to_parser
    clang_has_z3 = analyzer_types.is_z3_capable()
  File "c:\python\lib\site-packages\codechecker_analyzer\analyzers\analyzer_types.py", line 73, in is_z3_capable
    enabled_analyzers, _ = check_supported_analyzers([ClangSA.ANALYZER_NAME])
  File "c:\python\lib\site-packages\codechecker_analyzer\analyzers\analyzer_types.py", line 144, in check_supported_anal
yzers
    context = analyzer_context.get_context()
  File "c:\python\lib\site-packages\codechecker_analyzer\analyzer_context.py", line 314, in get_context
    return Context()
  File "c:\python\lib\site-packages\codechecker_common\singleton.py", line 20, in __call__
    super(Singleton, cls).__call__(*args, **kwargs)
  File "c:\python\lib\site-packages\codechecker_analyzer\analyzer_context.py", line 68, in __init__
    machine = os.uname().machine
AttributeError: module 'os' has no attribute 'uname'

**Expected behaviour**
CodeChecker will analyze the source code

**Desktop (please complete the following information)**
 - OS: Windows 64

**Comment by bruntib** [comment]
This has been fixed by #4012. Please, try the latest master version. The next release is coming soon, which contains this fix too. I close this ticket, but feel free to reopen if the problem still occurs.
