### ISSUE TITLE
CodeChecker server init: TypeError: BaseContext.Pool() unexpected argument 'max_workers'

### ISSUE THREAD

**Issue by lff5** [Ericsson/codechecker#4338]
When i run `CodeChecker server` without no other argument, I get following output:

```
[INFO 2024-09-06 18:59] - Checking configuration database ...
[INFO 2024-09-06 18:59] - Database is up to date.
[INFO 2024-09-06 18:59] - Status of products:
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Product endpoint | Database status         | Database location                           | Schema version in the database | Schema version in the package
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Default          | Database is up to date. | /Users/username/.codechecker/Default.sqlite | c3dad71f8e6b (up to date)      | c3dad71f8e6b                 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/codechecker_common/cli.py", line 209, in main
    sys.exit(args.func(args))
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/codechecker_server/cmd/server.py", line 430, in __handle
    main(args)
  File "/opt/homebrew/lib/python3.11/site-packages/codechecker_server/cmd/server.py", line 1158, in main
    server_init_start(args)
  File "/opt/homebrew/lib/python3.11/site-packages/codechecker_server/cmd/server.py", line 1113, in server_init_start
    server.start_server(args.config_directory,
  File "/opt/homebrew/lib/python3.11/site-packages/codechecker_server/server.py", line 1113, in start_server
    all_success, fails = _do_db_cleanups(config_sql_server,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/codechecker_server/server.py", line 734, in _do_db_cleanups
    with Pool(max_workers=thr_count) as executor:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseContext.Pool() got an unexpected keyword argument 'max_workers'
```

**My environment**
Apple M2 Pro, Ventura 13.6.7
Installed via brew
Browser doesn't matter, I never got the server running.

`CodeChecker version`
```
[INFO 2024-09-06 19:08] - CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.24.0                                  
Package build date   | 2024-08-27T14:08                        
Git commit ID (hash) | ea795071d62637c69300f4528b6c46c75b2274bc
Git tag information  | 6.24                                    
---------------------------------------------------------------

[INFO 2024-09-06 19:08] - CodeChecker web version:
------------------------------------------------------------------------------
Kind                                | Version                                 
------------------------------------------------------------------------------
Base package version                | 6.24.0                                  
Package build date                  | 2024-08-27T14:08                        
Git commit ID (hash)                | ea795071d62637c69300f4528b6c46c75b2274bc
Git tag information                 | 6.24                                    
Server supported Thrift API version | 6.58                                    
Client Thrift API version           | 6.58                                    
------------------------------------------------------------------------------
```

**To Reproduce**
I installed CodeChecker via PIP.
Ran analyse on a zephyr project which was successful.
tried to start the server with `CodeChecker server` with no arguments and immediately got this error. Console output is from the second run, first run ended the same way, it just had some info on config files, new user/pass and warning on security risk and chmod command.

**Comment by whisperity** [comment]
Affecting all versions up to 6.26.1 on MacOS 15.x releases.
Until a solution is found, the Docker version of the web server seems to work properly. You just need to mention `--arch amd64` to `docker run`, because there are no `arm64` builds of the server package.
