### ISSUE TITLE
cmd sum fails on "TApplicationException: Unknown function getAuthParameters"

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#471]
I do have an instance running on the system

```̀
$ CodeChecker cmd sum -p 8001 -a
Traceback (most recent call last):
  File "/data/jenkins/codechecker_package/CodeChecker/cc_bin/CodeChecker.py", line 514, in main
    args.func(args)
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/cmdline_client/cmd_line_client.py", line 321, in handle_list_result_types
    client = setupClient(args.host, args.port, '/')
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/cmdline_client/cmd_line_client.py", line 117, in setupClient
    auth_response = auth_client.getAuthParameters()
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/cmdline_client/authentication_helper.py", line 49, in wrapper
    res = func(*args, **kwargs)
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_gen/Authentication/codeCheckerAuthentication.py", line 48, in getAuthParameters
    return self.recv_getAuthParameters()
  File "/data/jenkins/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_gen/Authentication/codeCheckerAuthentication.py", line 63, in recv_getAuthParameters
    raise x
TApplicationException: Unknown function getAuthParameters
```̀

**Comment by whisperity** [comment]
Is the server and the client the same version?

It looks like the client is newer (wants to query authentication modes from the server) than the server (it does not support that feature).

**Comment by sylvestre** [comment]
Oh, yeah, sorry, this is the issue.
Maybe the client should check the version and provide a better error message.
Sorry for the noise :(

**Comment by gyorb** [comment]
I reopen this. We should handle this error better.

**Comment by whisperity** [comment]
I am pushing a patch just now. Sorry I had to leave home before being able to push.

**Comment by gyorb** [comment]
Thanks for the feedback @sylvestre and for the fix @whisperity.
