### ISSUE TITLE
CTU storage of Xerces fails

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#878]
When analyzing Apache Xerces 3.1 with `--ctu`, for some reason, the created ZIP is bogus.
The client properly sends the data through, and on the server's log, the following data is printed:

```
[14:00] - 127.0.0.1:55233 -- [Anonymous] POST /Xerces/CodeCheckerService
Traceback (most recent call last):
  File "/home/compass/srv/CodeCheckerv6/workspace/install/CodeChecker/lib/python2.7/gencodechecker/codeCheckerDBAccess/codeCheckerDBAccess.py", line 2478, in 
process_massStoreRun
    result.success = self._handler.massStoreRun(args.run_name, args.version, args.zipfile, args.force)
  File "/home/compass/srv/CodeCheckerv6/workspace/install/CodeChecker/lib/python2.7/libcodechecker/profiler.py", line 45, in release_wrapper
    res = function(*args, **kwargs)
  File "/home/compass/srv/CodeCheckerv6/workspace/install/CodeChecker/lib/python2.7/libcodechecker/server/client_db_access_handler.py", line 2355, in massStor
eRun
    store_handler.collect_paths_events(report, file_ids)
  File "/home/compass/srv/CodeCheckerv6/workspace/install/CodeChecker/lib/python2.7/libcodechecker/analyze/store_handler.py", line 106, in collect_paths_event
s
    file_path = files[event['location']['file']]
IndexError: list index out of range
[14:02] - Session timeout for run 4
```

Apparently, something in the ZIP is missing, a file is not created or something.

> Note, that this analysis is done into a server where "normal" Xerces analysis is already done, so there are some files already present on the server.

----

Moreover, the client prints the following:

```
[14:00] - ----==== Summary ====----
[14:00] - Total compilation commands: 1262
[14:00] - Successfully analyzed
[14:00] -   clangsa: 631
[14:00] -   clang-tidy: 631
[14:00] - ----=================----
[14:00] - Analysis length: 796.202292919 sec.
[14:00] - Analysis finished.
[14:00] - To view results in the terminal use the "CodeChecker parse" command.
[14:00] - To store results use the "CodeChecker store" command.
[14:00] - See --help and the user guide for further options about parsing and storing the reports.
[14:00] - ----=================----
[14:00] - Storing analysis results for run 'Xerces_3.1.1_CTU'
[14:02] - Storage failed: Internal error
```

What is a big problem, however, that even though `Storage failed: Internal error` is printed, the **`store` command exits with `0`**, so scripting this tool at this point is problematic.

**Comment by whisperity** [comment]
This is not yet fixed, the client still appears to return `0` even if the storage on the server's side fails.
