### ISSUE TITLE
change review status name

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#908]
Change `won't fix` label to `intentional`.

**Comment by whisperity** [comment]
Some test files seemingly haven't been updated:

```
01:31:59 ======================================================================
01:31:59 ERROR: Filter by review status.
01:31:59 ----------------------------------------------------------------------
01:31:59 Traceback (most recent call last):
01:31:59   File "/home/checker/jenkins-workspace/master-64bit/codechecker-github/tests/functional/report_viewer_api/test_report_filter.py", line 220, in test_filter_review_status
01:31:59     status = get_status(review_status)
01:31:59   File "/home/checker/jenkins-workspace/master-64bit/codechecker-github/tests/functional/report_viewer_api/test_report_filter.py", line 26, in get_status
01:31:59     return shared.ttypes.ReviewStatus._NAMES_TO_VALUES[name]
01:31:59 KeyError: u'WONT_FIX'
```

**Comment by gyorb** [comment]
I've updated the internal tests too.
